// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MsisdnsColumns holds the columns for the "msisdns" table.
	MsisdnsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "primary_identity", Type: field.TypeString},
		{Name: "primary_identity_type", Type: field.TypeEnum, Enums: []string{"Prepaid", "Postpaid"}},
		{Name: "provisioned", Type: field.TypeBool, Default: false},
	}
	// MsisdnsTable holds the schema information for the "msisdns" table.
	MsisdnsTable = &schema.Table{
		Name:       "msisdns",
		Columns:    MsisdnsColumns,
		PrimaryKey: []*schema.Column{MsisdnsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "roles", Type: field.TypeEnum, Enums: []string{"Developer", "ProductManager", "Architect"}},
		{Name: "active", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MsisdnsTable,
		UsersTable,
	}
)

func init() {
}
