// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"huspass/ent/msisdn"
	"huspass/ent/predicate"
	"huspass/model"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MsisdnUpdate is the builder for updating Msisdn entities.
type MsisdnUpdate struct {
	config
	hooks    []Hook
	mutation *MsisdnMutation
}

// Where appends a list predicates to the MsisdnUpdate builder.
func (mu *MsisdnUpdate) Where(ps ...predicate.Msisdn) *MsisdnUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetPrimaryIdentity sets the "primary_identity" field.
func (mu *MsisdnUpdate) SetPrimaryIdentity(s string) *MsisdnUpdate {
	mu.mutation.SetPrimaryIdentity(s)
	return mu
}

// SetPrimaryIdentityType sets the "primary_identity_type" field.
func (mu *MsisdnUpdate) SetPrimaryIdentityType(mit model.PrimaryIdentityType) *MsisdnUpdate {
	mu.mutation.SetPrimaryIdentityType(mit)
	return mu
}

// SetProvisioned sets the "provisioned" field.
func (mu *MsisdnUpdate) SetProvisioned(b bool) *MsisdnUpdate {
	mu.mutation.SetProvisioned(b)
	return mu
}

// SetNillableProvisioned sets the "provisioned" field if the given value is not nil.
func (mu *MsisdnUpdate) SetNillableProvisioned(b *bool) *MsisdnUpdate {
	if b != nil {
		mu.SetProvisioned(*b)
	}
	return mu
}

// Mutation returns the MsisdnMutation object of the builder.
func (mu *MsisdnUpdate) Mutation() *MsisdnMutation {
	return mu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MsisdnUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mu.hooks) == 0 {
		if err = mu.check(); err != nil {
			return 0, err
		}
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MsisdnMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mu.check(); err != nil {
				return 0, err
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			if mu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MsisdnUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MsisdnUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MsisdnUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MsisdnUpdate) check() error {
	if v, ok := mu.mutation.PrimaryIdentity(); ok {
		if err := msisdn.PrimaryIdentityValidator(v); err != nil {
			return &ValidationError{Name: "primary_identity", err: fmt.Errorf(`ent: validator failed for field "Msisdn.primary_identity": %w`, err)}
		}
	}
	if v, ok := mu.mutation.PrimaryIdentityType(); ok {
		if err := msisdn.PrimaryIdentityTypeValidator(v); err != nil {
			return &ValidationError{Name: "primary_identity_type", err: fmt.Errorf(`ent: validator failed for field "Msisdn.primary_identity_type": %w`, err)}
		}
	}
	return nil
}

func (mu *MsisdnUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   msisdn.Table,
			Columns: msisdn.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: msisdn.FieldID,
			},
		},
	}
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.PrimaryIdentity(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: msisdn.FieldPrimaryIdentity,
		})
	}
	if value, ok := mu.mutation.PrimaryIdentityType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: msisdn.FieldPrimaryIdentityType,
		})
	}
	if value, ok := mu.mutation.Provisioned(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: msisdn.FieldProvisioned,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{msisdn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// MsisdnUpdateOne is the builder for updating a single Msisdn entity.
type MsisdnUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MsisdnMutation
}

// SetPrimaryIdentity sets the "primary_identity" field.
func (muo *MsisdnUpdateOne) SetPrimaryIdentity(s string) *MsisdnUpdateOne {
	muo.mutation.SetPrimaryIdentity(s)
	return muo
}

// SetPrimaryIdentityType sets the "primary_identity_type" field.
func (muo *MsisdnUpdateOne) SetPrimaryIdentityType(mit model.PrimaryIdentityType) *MsisdnUpdateOne {
	muo.mutation.SetPrimaryIdentityType(mit)
	return muo
}

// SetProvisioned sets the "provisioned" field.
func (muo *MsisdnUpdateOne) SetProvisioned(b bool) *MsisdnUpdateOne {
	muo.mutation.SetProvisioned(b)
	return muo
}

// SetNillableProvisioned sets the "provisioned" field if the given value is not nil.
func (muo *MsisdnUpdateOne) SetNillableProvisioned(b *bool) *MsisdnUpdateOne {
	if b != nil {
		muo.SetProvisioned(*b)
	}
	return muo
}

// Mutation returns the MsisdnMutation object of the builder.
func (muo *MsisdnUpdateOne) Mutation() *MsisdnMutation {
	return muo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MsisdnUpdateOne) Select(field string, fields ...string) *MsisdnUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Msisdn entity.
func (muo *MsisdnUpdateOne) Save(ctx context.Context) (*Msisdn, error) {
	var (
		err  error
		node *Msisdn
	)
	if len(muo.hooks) == 0 {
		if err = muo.check(); err != nil {
			return nil, err
		}
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MsisdnMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = muo.check(); err != nil {
				return nil, err
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			if muo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = muo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, muo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Msisdn)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from MsisdnMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MsisdnUpdateOne) SaveX(ctx context.Context) *Msisdn {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MsisdnUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MsisdnUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MsisdnUpdateOne) check() error {
	if v, ok := muo.mutation.PrimaryIdentity(); ok {
		if err := msisdn.PrimaryIdentityValidator(v); err != nil {
			return &ValidationError{Name: "primary_identity", err: fmt.Errorf(`ent: validator failed for field "Msisdn.primary_identity": %w`, err)}
		}
	}
	if v, ok := muo.mutation.PrimaryIdentityType(); ok {
		if err := msisdn.PrimaryIdentityTypeValidator(v); err != nil {
			return &ValidationError{Name: "primary_identity_type", err: fmt.Errorf(`ent: validator failed for field "Msisdn.primary_identity_type": %w`, err)}
		}
	}
	return nil
}

func (muo *MsisdnUpdateOne) sqlSave(ctx context.Context) (_node *Msisdn, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   msisdn.Table,
			Columns: msisdn.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: msisdn.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Msisdn.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, msisdn.FieldID)
		for _, f := range fields {
			if !msisdn.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != msisdn.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.PrimaryIdentity(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: msisdn.FieldPrimaryIdentity,
		})
	}
	if value, ok := muo.mutation.PrimaryIdentityType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: msisdn.FieldPrimaryIdentityType,
		})
	}
	if value, ok := muo.mutation.Provisioned(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: msisdn.FieldProvisioned,
		})
	}
	_node = &Msisdn{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{msisdn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
