// Code generated by ent, DO NOT EDIT.

package ent

import (
	"huspass/ent/msisdn"
	"huspass/ent/schema"
	"huspass/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	msisdnFields := schema.Msisdn{}.Fields()
	_ = msisdnFields
	// msisdnDescPrimaryIdentity is the schema descriptor for primary_identity field.
	msisdnDescPrimaryIdentity := msisdnFields[1].Descriptor()
	// msisdn.PrimaryIdentityValidator is a validator for the "primary_identity" field. It is called by the builders before save.
	msisdn.PrimaryIdentityValidator = msisdnDescPrimaryIdentity.Validators[0].(func(string) error)
	// msisdnDescProvisioned is the schema descriptor for provisioned field.
	msisdnDescProvisioned := msisdnFields[3].Descriptor()
	// msisdn.DefaultProvisioned holds the default value on creation for the provisioned field.
	msisdn.DefaultProvisioned = msisdnDescProvisioned.Default.(bool)
	// msisdnDescID is the schema descriptor for id field.
	msisdnDescID := msisdnFields[0].Descriptor()
	// msisdn.DefaultID holds the default value on creation for the id field.
	msisdn.DefaultID = msisdnDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescActive is the schema descriptor for active field.
	userDescActive := userFields[4].Descriptor()
	// user.DefaultActive holds the default value on creation for the active field.
	user.DefaultActive = userDescActive.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
