// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di_context

import (
	"huspass/api"
	"huspass/external"
	"huspass/repo"
)

// Injectors from wire.go:

func DependencyProvider() (*api.Service, error) {
	host, err := external.HostProvider()
	if err != nil {
		return nil, err
	}
	msisdnRepositoryImpl, err := repo.DatabaseImplProvider(host)
	if err != nil {
		return nil, err
	}
	userRepoImpl, err := repo.UserDBImplProvider(host)
	if err != nil {
		return nil, err
	}
	service, err := api.ServiceProvider(msisdnRepositoryImpl, userRepoImpl)
	if err != nil {
		return nil, err
	}
	return service, nil
}
