// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Msisdn is the predicate function for msisdn builders.
type Msisdn func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
